### ISSUE TITLE
[social] [google] Internal server error - AM using google

### ISSUE THREAD

**Issue by jcverazzi** [gravitee-io/graviteeio-access-management#471]
### Expected Behavior
Connect with google on APIM portal, using google oauth2 provider on AM.

### Current Behavior
Login form displays well. I can click on my profile, but then I have a screen "Internal server error".

![image](https://user-images.githubusercontent.com/45290522/49375313-3e2f0980-f704-11e8-85c5-ce8d6771fa26.png)
![image](https://user-images.githubusercontent.com/45290522/49375366-5bfc6e80-f704-11e8-87ba-be3e6d3c4d4a.png)
![image](https://user-images.githubusercontent.com/45290522/49375411-7df5f100-f704-11e8-93bd-414c8f530fc6.png)
The URL with this error is http://<AM_GATEWAY>/<DOMAIN>/login/callback?provider=03a53eeb-d341-4ab2-a53e-ebd3417ab2ec&code=<CODE_FOUND>&scope=openid%20email%20profile%20https://www.googleapis.com/auth/plus.me%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=<domain.com>&session_state=8672d74c4071e621557611d577ef8d184f0b19ff..d843&prompt=consent
Error in gateway gravitee.log:
```
11:32:33.528 [vert.x-eventloop-thread-7] [] ERROR i.g.a.g.h.v.a.p.OAuth2ClientAuthenticationProvider - Unable to authenticate oauth2 provider
io.gravitee.am.service.exception.authentication.BadCredentialsException: Bad Request
	at io.gravitee.am.identityprovider.oauth2.authentication.OAuth2GenericAuthenticationProvider.lambda$null$2(OAuth2GenericAuthenticationProvider.java:110)
	at io.vertx.reactivex.core.http.HttpClient$15.handle(HttpClient.java:501)
	at io.vertx.reactivex.core.http.HttpClient$15.handle(HttpClient.java:499)
	at io.vertx.core.http.impl.HttpClientRequestImpl.doHandleResponse(HttpClientRequestImpl.java:443)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleResponse(HttpClientRequestBase.java:143)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponse(Http1xClientConnection.java:471)
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:109)
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:33)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Here's my provider config on AM:
![image](https://user-images.githubusercontent.com/45290522/49376181-b5659d00-f706-11e8-8595-f4be284cf65e.png)

I also tried:
```
curl \
	-d redirect_uri=<REDIRECT_URI> \
	-d client_id=<CLIENT_ID> \
	-d client_secret=<CLIENT_SECRET> \
	-d code=<CODE_FOUND> \
	-d prompt=none \
	-d grant_type=authorization_code https://www.googleapis.com/oauth2/v4/token
```

I got the <CODE_FOUND> from the URL returning the "Internal server error".

This CURL call is returning me a token. And then I no longer have the "Internal server error" screen. Instead I have a "Session expired, redirecting to home", same as my AD problem before.

**Comment by brasseld** [comment]
Thanks for your feedback @jcverazzi
