### ISSUE TITLE
Error while enabling https in gateway

### ISSUE THREAD

**Issue by saraAlizadeh** [gravitee-io/graviteeio-access-management#494]
I need to enable https and I did it just like documentation.
```
keytool -genkey \
  -alias test \
  -keyalg RSA \
  -keystore server-keystore.jks \
  -keysize 2048 \
  -validity 360 \
  -dname CN=localhost \
  -keypass secret \
  -storepass secret
```

and then added 
```yaml
http:
  host: x.x.x.x
  port: 8092
  idleTimeout: 0
  tcpKeepAlive: true
  compressionSupported: false
  instances: 0
  secured: true
  ssl:
    clientAuth: false
    keystore:
      path: /path/to/keystore.jks
      password: secret
    truststore:
      path:
      password:
```

the started the am gateway service an got this error log:

```
00:40:57.636 [graviteeio-node] [] INFO  i.g.am.gateway.node.GatewayNode - Gravitee.io - AM Gateway id[70394693-772f-4e14-b946-93772f5e14c9] version[2.1.0] pid[7897] build[189#${env.GIT_COMMIT}] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.192-b12] started in 1760 ms.
00:40:57.752 [vert.x-eventloop-thread-7] [] ERROR i.g.a.g.vertx.VertxEmbeddedContainer - Unable to start HTTP server
io.vertx.core.file.FileSystemException: java.io.IOException: Is a directory
	at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:740)
	at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:732)
	at io.vertx.core.file.impl.FileSystemImpl.readFileBlocking(FileSystemImpl.java:296)
	at io.vertx.core.net.impl.KeyStoreHelper.lambda$create$0(KeyStoreHelper.java:77)
	at io.vertx.core.net.impl.KeyStoreHelper.loadJKSOrPKCS12(KeyStoreHelper.java:268)
	at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:83)
	at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:115)
	at io.vertx.core.net.TrustOptions.getTrustManagerFactory(TrustOptions.java:43)
	at io.vertx.core.net.impl.SSLHelper.getTrustMgrFactory(SSLHelper.java:322)
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:453)
	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:482)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:243)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:201)
	at io.vertx.reactivex.core.http.HttpServer.listen(HttpServer.java:278)
	at io.gravitee.am.gateway.vertx.GraviteeVerticle.start(GraviteeVerticle.java:53)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.file.Files.read(Files.java:3105)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:736)
	... 22 common frames omitted
00:40:57.753 [graviteeio-finalizer] [] INFO  i.g.a.g.container.GatewayContainer - Shutting-down Gravitee.io - AM Gateway...
00:40:57.753 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Gravitee.io - AM Gateway is stopping
00:40:57.754 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: VertxEmbeddedContainer
00:40:57.754 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: Reactor
00:40:57.754 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.am.gateway.reactor.impl.DefaultReactor
00:40:57.754 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: ReporterManager
00:40:57.754 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service Reporter service
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: ManagementService
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service Node Management API service
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: ServiceManager
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service Plugins - Services Manager
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service Sync Service
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service Node Health-check service
00:40:57.756 [graviteeio-finalizer] [] INFO  i.g.n.s.monitoring.MonitoringService - Stop node monitor
00:40:57.767 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service Monitoring Service
00:40:57.767 [graviteeio-finalizer] [] INFO  i.g.n.s.monitoring.MonitoringService - Stop node monitor : DONE
00:40:57.768 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: PluginRegistry
00:40:57.768 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.plugin.core.internal.PluginRegistryImpl
00:40:57.768 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Stopping component: PluginEventListener
00:40:57.768 [graviteeio-finalizer] [] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.plugin.core.internal.PluginEventListener
00:40:57.768 [graviteeio-finalizer] [] INFO  i.g.am.gateway.node.GatewayNode - Gravitee.io - AM Gateway stopped
```

can anyone help me on this?

**Comment by saraAlizadeh** [comment]
well I created keystore and truststore using bellow command:
1.Generate keystore(At server):
`keytool -genkey -alias bmc -keyalg RSA -keystore KeyStore.jks -keysize 2048`
2.Generate new ca-cert and ca-key:
`openssl req -new -x509 -keyout ca-key -out ca-cert`
3.Extracting cert/creating cert sign req(csr):
`keytool -keystore KeyStore.jks -alias bmc -certreq -file cert-file`
4.Sign the “cert-file” and cert-signed wil be the new cert:
`openssl x509 -req -CA ca-cert -CAkey ca-key -in cert-file -out \
       cert-signed -days 365 -CAcreateserial -passin pass:yourpass`
5.importing the ca-cert to keystore file:
`keytool -keystore KeyStore.jks -alias CARoot -import -file ca-cert`
6.import cert-signed to keystore:
`keytool -keystore KeyStore.jks -alias bmc -import -file cert-signed`
`keytool -keystore truststore.jks -alias bmc -import -file ca-cert `

and the added their oath to am gateway and am management api configs. both services are up now.
now how can I connect to portal? `https:myIP` gives me this error:
`Error code: SSL_ERROR_RX_RECORD_TOO_LONG`

**Comment by saraAlizadeh** [comment]
I changed some configs in constant.json and now am management api logs these warnings:
`09:14:37.357 [graviteeam-listener-45] [] WARN  org.eclipse.jetty.http.HttpParser - Illegal character 0x16 in state=START for buffer HeapByteBuffer@7e3bd74d[p=1,l=162,c=8192,r=161]={\x16<<<\x03\x01\x00\x9d\x01\x00\x00\x99\x03\x03N}3\x17\xCc\x18P...\x03\x05\x03\x06\x03\x04\x01\x05\x01\x06\x01\x02\x03\x02\x01>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
09:14:37.358 [graviteeam-listener-45] [] WARN  org.eclipse.jetty.http.HttpParser - bad HTTP parsed: 400 Illegal character 0x16 for HttpChannelOverHttp@4776bba1{r=0,c=false,a=IDLE,uri=null}`
I have to mention that I checked [this issue](https://github.com/gravitee-io/issues/issues/1394) but I could not find relevance.

**Comment by saraAlizadeh** [comment]
I solved this issue. we need to enable ssl for apache httpd, too.
to do this create a virtual host which listens to port 443 and its document root is gravitee management web ui directory.
use this link as a manual.
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-apache-for-centos-7
